### ISSUE TITLE
Automatisches Deployment

### ISSUE THREAD

**Issue by JM-Lemmi** [DU4L/CTFNote#22]

**Comment by frereit** [comment]
```
on:
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]
```
currently only runs on PR to main, but should run on PR to develop as well
